name: Run Linting Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Super-linter
      uses: super-linter/super-linter@v6.2.0
      continue-on-error: true
      env:
        VALIDATE_ALL_CODEBASE: false
        VALIDATE_PYTHON_FLAKE8: true
        VALIDATE_PYTHON_ISORT: true