name: Run Linting Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black isort

    - name: Run Flake8
      run: flake8 .

    - name: Run Black
      run: black --check .

    - name: Run isort
      run: isort . --check-only