name: Run Linting Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
  

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensures you have the full git history

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Node.js 14 is recommended by MegaLinter documentation

    - name: MegaLinter
      uses: nvuillam/mega-linter-runner@v5
      env:
        ENABLE: PYTHON
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VALIDATE_PYTHON_BLACK: true
        VALIDATE_PYTHON_ISORT: true
        VALIDATE_PYTHON_FLAKE8: true
